 PROGRAM test3
  IMPLICIT NONE
  INTEGER :: ierr
  INTEGER :: stdout
  REAL*8, ALLOCATABLE :: f1(:),s1(:)
  REAL*8, ALLOCATABLE :: f_glob(:,:), s_glob(:,:), a_glob(:,:)
! space for inversion
  REAL*8, ALLOCATABLE :: work(:,:),am1(:,:)
  INTEGER, ALLOCATABLE :: ipiv(:)
! space for diagonalization
  REAL*8, ALLOCATABLE :: vr(:,:),vl(:,:)
  REAL*8, ALLOCATABLE :: wr(:),wi(:),workd(:),eA(:),wt(:),Ct(:,:),C(:,:)
  REAL*8 :: vt,norm

  INTEGER :: n1,n2,dimI,dim12,dimII    ! size of arrays representing upper-right triangle of matrices
  INTEGER :: n  ! size of the matrices
  INTEGER :: rigid  ! if 1 the system is rigid
  !
  integer :: nargs
  CHARACTER(LEN=80) :: arg
  character(len=80) :: filename
  integer :: FSinput,i,j,i2,j2,k,l,info,isort,eval_output,evec_output
  !
  !   default parameter 
  !
  n1 = 1
  n2 = 1
  rigid = 0
  !
  nargs = command_argument_count()
  if(nargs ==10) then
  do i = 1, nargs - 1
     CALL get_command_argument(i, arg)
     IF( TRIM( arg ) == '-n1' ) THEN
        CALL get_command_argument(i+1, arg)
        READ( arg, * ) n1
     END IF
     IF( TRIM( arg ) == '-n2' ) THEN
        CALL get_command_argument(i+1, arg)
        READ( arg, * ) n2
     END IF
     IF( TRIM( arg ) == '-f' ) THEN
        CALL get_command_argument(i+1, arg)
        READ( arg, * ) filename
        FSinput=86
        OPEN (UNIT=FSinput, FILE=trim(filename), STATUS='old', &
         FORM='unformatted', iostat=ierr)
        if(ierr /= 0) then
         write(6,*) ' Error reading filename '//trim(filename), ierr
         stop 1
        endif
     END IF
     IF( TRIM( arg ) == '-o1' ) THEN
        CALL get_command_argument(i+1, arg)
        READ( arg, * ) filename
        eval_output=87
        OPEN (UNIT=eval_output, FILE=trim(filename), STATUS='new', &
         FORM='formatted', iostat=ierr)
        if(ierr /= 0) then
         write(6,*) ' Error opening filename '//trim(filename), ierr
         stop 1
        endif
     END IF
     IF( TRIM( arg ) == '-o2' ) THEN
        CALL get_command_argument(i+1, arg)
        READ( arg, * ) filename
        evec_output=88
        OPEN (UNIT=evec_output, FILE=trim(filename), STATUS='new', &
         FORM='formatted', iostat=ierr)
        if(ierr /= 0) then
         write(6,*) ' Error opening filename '//trim(filename), ierr
         stop 1
        endif
     END IF
     IF( TRIM( arg ) == '-rigid' ) THEN
        CALL get_command_argument(i+1, arg)
        READ( arg, * ) rigid
     END IF
  end do
  else
   write(6,*) 'Required 5 parameters:'
   write(6,*) 'n1 (-n1), n2 (-n2), F/S file name (-f), '
   write(6,*) 'output eigenvalues (-o1), output eigenvectors (-o2)'
   stop 1
  end if

  dimI = n1*(n1+1)/2
  dim12 = n1*n2
  dimII = n2*(n2+1)/2
  n=n1+n2

! Opening and reading the S and F matrices generated by mdan
! only first order so far
   allocate(s_glob(n,n)) ! matrix S, global
   allocate(f_glob(n,n)) ! matrix F, global
   allocate(a_glob(n,n)) ! matrix a, global
   allocate(f1(dimI))
   allocate(s1(dimI))

   read(FSinput) f1
   read(FSinput) s1

   k=0
   norm=0.
   do i=1,n1
    do j=i,n1
     k=k+1
     f_glob(i,j) = f1(k)
     f_glob(j,i) = f_glob(i,j)
     s_glob(i,j) = s1(k)
     s_glob(j,i) = s_glob(i,j)
    enddo
    norm=norm+s_glob(i,i)
   enddo
!   write(87,*) 'Trace of S^{I,I}= ',norm
!   write(87,*) 'final k= ',k
   
   close(FSinput)
   deallocate(f1)
   deallocate(s1)
   
!  stop 0

   ALLOCATE( am1( n, n ) )
   ALLOCATE( work( n, n ) )
   ALLOCATE( ipiv( n ) )
   if (rigid == 0) then
    am1 = s_glob
    call dgetrf(n,n,am1,n,ipiv,info)
!    write(87,*) 'DGETRF: info= ',info
    if(info /= 0) then
     stop 'Singular matrix S.'
    endif
    call dgetri(n,am1,n,ipiv,work,n,info)
!    write(87,*) 'DGETRI: info= ',info

!! test if S^{-1} S = I:
!   a_glob=MATMUL(am1,s_glob)
!   do i=1,n
!    do j=1,n
!     write(87,*) am1(i,j),a_glob(i,j)
!    enddo
!   enddo
!   stop 'S inversion done.'
    a_glob=MATMUL(am1,f_glob)
   else
    am1 = f_glob
    call dgetrf(n,n,am1,n,ipiv,info)
!    write(87,*) 'DGETRF: info= ',info
    if(info /= 0) then
     stop 'Singular matrix F.'
    endif
    call dgetri(n,am1,n,ipiv,work,n,info)
!    write(87,*) 'DGETRI: info= ',info

!! test if F^{-1} F = I:
!    a_glob=MATMUL(am1,f_glob)
!    do i=1,n
!     do j=1,n
!      write(87,*) am1(i,j),a_glob(i,j)
!     enddo
!    enddo
!    stop 'F inversion done.'
!    a_glob=MATMUL(am1,s_glob)

   endif
!   stop 0

   deallocate(work)
   deallocate(ipiv)

! Diagonalization of S^{-1}F:

   ALLOCATE( wr( n ) )
   ALLOCATE( wi( n ) )
   ALLOCATE( vr( n, n ) )
   ALLOCATE( workd( 4*n ) )
   call dgeev('N','V',n,a_glob,n,wr,wi,vl,n,vr,n,workd,size(workd,1),info)
   deallocate(workd)
   ALLOCATE( Ct( n, n ) )
   C=MATMUL(s_glob,vr)
   Ct=transpose(vr)
   f_glob=MATMUL(Ct,C)
   do j=1,N
    norm=1.d0/dsqrt(f_glob(j,j))
    do i=1,N
     vr(i,j) = vr(i,j)*norm
    enddo
   enddo
   ! check if Ct*S*C = I
!   C=MATMUL(s_glob,vr)
!   Ct=transpose(vr)
!   f_glob=MATMUL(Ct,C)
!   do i=1,N
!    do j=1,N
!     write(6,*) 'Ct*S*C= ',f_glob(i,j)
!    enddo
!   enddo

   deallocate(Ct)

   allocate(wt(n))
   if(rigid == 0) then
   else
    wt=1./wr
    wr=wt
   endif

   isort=1
   if(isort == 1) then
   allocate(eA(n))
   wt=1./wr
   do i=1,n-1
    k=i
    vt = wt(k)
    do j=i+1,n
     if (wt(j) > vt) then
      k=j
      vt = wt(k)
     endif
    enddo
    if (k /= i) then
     wt(k) = wt(i)
     wt(i) = vt
     eA = vr(:,i)
     vr(:,i) = vr(:,k)
     vr(:,k) = eA
    endif
   enddo
   wr=1./wt
   endif

   do i=1,n
    write(87,*) wr(i)
   enddo
   do i=1,n
    do j=1,n
     write(88,*) vr(i,j)
    enddo
   enddo

  close(eval_output)
  close(evec_output)

  stop 0

end program test3
